name: Publish Python Package

on:
  push:
    tags:
      - 'python-v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # needed for PyPI trusted publishing (OIDC)
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install build
      - name: Verify environment
        working-directory: python
        run: |
          python -c "import sys, pkgutil; print('Python', sys.version); import requests; print('requests OK', requests.__version__)"
          pip list
      - name: Run tests
        working-directory: python
        run: |
          pytest -q
      - name: Build package
        run: |
          cd python
          python -m build
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
          verbose: true
